"""
semafor_ha_momentum_20260910.py - Heiken Ashi Smoothed + Semafor + RSI momentum.

Location:  ~/src/trading/strategies/experimental/semafor_ha_momentum_20260910.py

Four layers, each answering a different question, and an entry needs all four
to agree. A smoothed Heiken Ashi ribbon says which way the macro tape leans; a
causally-confirmed swing pivot says the last leg has actually turned; RSI
leaving an extreme says momentum has re-engaged since that turn; and a close
crossing the fast EMA is the bar to act on. The pivot and the momentum gate
are the two that make this more than an EMA cross - they require the trigger
to arrive AFTER a structural low, not merely on a bar that happened to close
above a moving average.

================================================================================
STRATEGY SPECIFICATION & BACKTEST REQUEST  (filled from the 2026-09-10 request)
================================================================================
1. STRATEGY METADATA
   Strategy Name:       semafor_ha_momentum
   Strategy Archetype:  Trend-momentum breakout
   Primary Timeframe:   15m  (TIMEFRAME; the ladder is TIMEFRAMES)
   Target Assets:       the 19-contract matrix (SYMBOLS)

2. CORE CONCEPT & HYPOTHESIS
   A trend resumes from a structural pivot, not from an arbitrary bar. The
   inefficiency harvested is the gap between the pivot forming and the flow
   that follows it being recognised: participants who trade the level - stops
   under the swing low, breakout orders above it - act on confirmation, and
   confirmation is late by construction. It persists because the delay is
   structural rather than a view. The smoothed Heiken Ashi ribbon exists to
   refuse the setups that form against the macro lean, which is where a pivot
   is a pause in a larger move rather than the start of one.

3. INDICATORS & PARAMETER GRID
   Heiken Ashi Smoothed - EMA({ha_period}) over raw OHLC, Heiken Ashi built on
       the result, then EMA({ha_smooth}) over the HA candles. Bullish when
       close > HA_close AND the HA candle is green AND HA_close is rising.
   Semafor pivots      - a swing low/high over {swing_lookback} bars either
       side, CONFIRMED {swing_lookback} bars after it forms. See the causality
       note below; this is the whole reason the module is not a repainter.
   EMA({fast_ema})     - the micro trigger.
   RSI({rsi_period}), Wilder - the momentum gate at {rsi_oversold} /
       {rsi_overbought}.
   ATR(14), Wilder     - the protective stop only, never a signal level.

4. ENTRY & EXIT EXECUTION RULES
   Long:   Close crosses ABOVE EMA({fast_ema}), with a confirmed swing LOW
           within the last {momentum_window} bars, and RSI crossing above
           {rsi_oversold} at or after that pivot.
   Short:  Close crosses BELOW EMA({fast_ema}), with a confirmed swing HIGH
           within the last {momentum_window} bars, and RSI crossing below
           {rsi_overbought} at or after that pivot.
   Filter: the Heiken Ashi macro lean, when use_macro_trend is on.
   Exit:   the fast-EMA midline cross (use_midline_exit), the opposite
           trigger, and optionally RSI entering the opposite zone
           (use_rsi_zone_exit). A protective ATR stop sits underneath all of
           them.
   Session Rules:   none modelled - NOT SPECIFIED in the request.
   Execution Fill:  next-bar open, engine-applied slippage and commission.

5. BACKTEST EXECUTION CONTROLS
   Repository defaults: in-sample 2013-01-01..2022-12-31, holdout 2023-01-01
   onward and untouched during optimisation, Version B evaluated against A.

FOUR PLACES THE REQUEST LEFT A DECISION, MADE HERE AND FLAGGED
---------------------------------------------------------------
**"Version A / Version B" IN THE REQUEST IS NOT THIS REPOSITORY'S A/B, and
conflating them would have produced a module that cannot be promoted.** The
Dual-Version Mandate is fixed: Version A is the rule-based baseline and
Version B is *the same signals* with an ML filter over them, generated by
`backtest/promote.py`'s wrapper and adopted only if it beats A out of sample.
The request's "Version A: fixed stop / Version B: trailing stop with an RSI
target" describes two RISK CONFIGURATIONS of one rule set. Written as versions
they would collide with the mandate and Stage 3 would certify two things that
are not the pair it compares. They are therefore PARAMETERS - `sl_atr_mult`,
`trailing`, `use_midline_exit`, `use_rsi_zone_exit` - and the two requested
configurations are named in `RISK_VARIANTS` below. DEFAULT_PARAMS is the
request's Version A, because that is the baseline this package is.

**The Semafor is confirmed, not centred, and that is the difference between
this module and a repainter.** A Semafor marks a swing low at bar i when
`low[i]` is the lowest of the {swing_lookback} bars either side of it - which
is not known until {swing_lookback} MORE bars have printed. Read at bar i it
is lookahead; every backtest built on the centred form buys the exact bottom
and reports a Sharpe nothing can reproduce. Here the pivot is located at
`i - swing_lookback` and becomes True at bar i, so a signal on bar i reads
only bars <= i. The cost is real and is the point: the entry is late by
{swing_lookback} bars relative to the drawn arrow, exactly as it would be
live. `test_signals_do_not_change_when_future_bars_are_removed` holds it.

**"RSI crossing above 30 within a rolling window after a swing low" needs an
ordering, not just a window.** Both events inside the last {momentum_window}
bars is not the same claim as the RSI cross arriving AFTER the pivot - the
second is the hypothesis, the first also admits a cross that preceded the low
it is supposed to confirm. Implemented as the ordering: `bars_since_rsi_cross
<= bars_since_pivot`, with both inside the window.

**"RSI opposite zone take-profit" is a SIGNAL exit, not a bracket.** The
engine has no target ORDERS - `from_signals` is driven by boolean masks and
fills at the next bar's open - so a target expressed as "RSI reaches 70" can
only be an exit mask, detected on the bar that reaches it and filled one bar
later. `tp_atr_mult` stays None in both variants rather than being fitted to
approximate it, and `use_rsi_zone_exit` carries the rule where it belongs.

WHAT THE ENGINE CANNOT DO, STATED SO NO DRAWDOWN IS MISREAD
------------------------------------------------------------
There are no stop or target ORDERS anywhere in this repository. A stop is
detected on the bar that breaches it and filled at the NEXT bar's open, not at
the stop price. Every drawdown figure this module produces is therefore a
next-bar-open drawdown and is worse than a resting-order backtest would show.
The trailing stop in `RISK_VARIANTS["B_trailing"]` is a state machine inside
`_walk_loop`, and its high-water mark starts at the FILL bar, not the signal
bar.
"""

from __future__ import annotations

import numpy as np
import pandas as pd


# ---------------------------------------------------------------------------
# The contract
# ---------------------------------------------------------------------------

#: The bar the DEFAULTS are set for, and the one the engine actually uses.
#: SINGULAR AND DECLARED: `agents.tier3_workers` reads
#: `getattr(module, "TIMEFRAME", None)` and its caller resolves
#: `explicit or info["timeframe"] or DEFAULT_TIMEFRAME`, where
#: DEFAULT_TIMEFRAME is "1d". Dropping this in favour of the plural below
#: would not raise - it would silently run an intraday momentum system on
#: DAILY bars. Nothing in this repository reads a `TIMEFRAMES`.
#:
#: 15m rather than 5m: the pivot is confirmed {swing_lookback} bars late, so
#: at 5m the entry arrives an hour after the low it is keyed to.
TIMEFRAME = "15m"

#: The ladder Stage 1 is meant to screen across. DESCRIPTIVE ONLY - no loader
#: or pipeline stage reads this name; a timeframe is selected per run with
#: `--timeframe`. Written down so the intended ladder is recoverable from the
#: module rather than from whoever typed the last command.
#:
#: 1m and 2m are absent deliberately: `intraday_start_year` exists because
#: pre-2013 1-minute data is sparse for ten symbols, and a 20-bar EMA ribbon
#: on those bars describes the gaps as much as the tape.
TIMEFRAMES = ["5m", "15m", "30m", "1h"]

#: The 19-contract matrix. `python -m backtest.specs` reports UNVERIFIED for
#: M2K and MYM alone, and neither is here.
#:
#: A DECLARATION OF WHERE THE PREMISE MIGHT HOLD, NOT A CLAIM THAT IT DOES.
#: Cross-sectional by default: each contract is its own simulation on its own
#: multiplier, tick size and commission, and symbols are never blended into
#: one equity curve. Two carried caveats from CLAUDE.md, neither caught by the
#: spec reconciler because it checks the CONTRACT rather than the bars: SI
#: definitions stop at 2016 and CL at 2025-12.
SYMBOLS = ["ES", "NQ", "YM", "RTY", "CL", "NG", "RB", "HO", "GC", "SI", "PL",
           "6E", "6B", "6J", "6S", "ZB", "ZN", "BTC", "ETH"]

STRATEGY_NAME = "SEMAFOR_HA_MOMENTUM"
STRATEGY_MODULE = "semafor_ha_momentum_20260910"

PORTFOLIO_GROUP = "Trend_Momentum"
CORRELATION_PROFILE = (
    "Spans every group in the matrix, so a basket drawn from it is only as "
    "diversified as the contracts chosen. The index names are one factor at "
    "four capitalisations and the energy names are another; routing sizes "
    "against that, not against the symbol count.")

#: The regime the premise NOMINATES. Stage 1 designates the real one by
#: measuring all four quadrants, and nothing here reads these. Quadrant ids
#: are `mdlib/regimes.py`'s: Q1 High-Vol/Trending, Q2 High-Vol/Ranging,
#: Q3 Low-Vol/Trending, Q4 Low-Vol/Ranging, 0 UNDEFINED (warm-up, not a
#: quadrant). A trend-momentum breakout nominates the TRENDING pair - in a
#: ranging regime a pivot-plus-EMA-cross is the range turning at its own edge,
#: which is what Gate R settles rather than this declaration.
TARGET_REGIMES = ("High Volatility / Trending", "Low Volatility / Trending")
TARGET_QUADRANTS = ("Q1", "Q3")

#: Wilder's ATR period, for the protective stop only. Fixed at 14 rather than
#: exposed: it never enters a signal level, so sweeping it would move only the
#: stop and confound the structure study it sits under.
ATR_PERIOD = 14

#: A stop nearer than this to the fill sits inside the bar's own noise and the
#: run measures the cost model rather than the strategy.
MIN_STOP_ATR_MULT = 0.25

#: The Heiken Ashi open recursion, `HA_open[i] = (HA_open[i-1] +
#: HA_close[i-1]) / 2`, is exactly an EWM with this alpha over HA_close
#: shifted one bar. Named rather than written as a bare 0.5 so the identity is
#: checkable against the definition instead of looking like a smoothing choice
#: somebody picked.
HA_OPEN_ALPHA = 0.5


DEFAULT_PARAMS = {
    "ha_period": 20,
    "ha_smooth": 5,
    "swing_lookback": 12,
    "fast_ema": 9,
    "rsi_period": 14,
    "rsi_oversold": 30.0,
    "rsi_overbought": 70.0,
    "momentum_window": 10,
    "use_macro_trend": True,
    "use_midline_exit": True,
    "use_rsi_zone_exit": False,
    "sl_atr_mult": 2.0,
    "tp_atr_mult": None,
    "trailing": False,
}

#: THE TWO CONFIGURATIONS THE REQUEST CALLED "Version A" AND "Version B".
#:
#: They are risk configurations of one rule set, NOT this repository's A/B -
#: see the module docstring. Named here so the request is recoverable from the
#: module and so a run can bind either without the numbers being retyped, and
#: kept out of PARAM_GRID because sweeping a bundle would confound which of
#: its four changes moved the result.
#:
#: `A_fixed` is DEFAULT_PARAMS and is what this package is certified as.
RISK_VARIANTS = {
    "A_fixed": {
        "sl_atr_mult": 2.0,
        "tp_atr_mult": None,
        "trailing": False,
        "use_midline_exit": True,
        "use_rsi_zone_exit": False,
    },
    "B_trailing": {
        "sl_atr_mult": 2.5,
        "tp_atr_mult": None,
        "trailing": True,
        "use_midline_exit": False,
        "use_rsi_zone_exit": True,
    },
}

#: The search space `backtest/run.py --scan` sweeps.
#:
#:     3 x 3 x 2 x 2 = 36 combinations
#:
#: Coarse on purpose. `variants_tested` travels with every result precisely so
#: a reader can see how large the search was that produced a Sharpe; a 400-cell
#: grid over the same bars is a machine for manufacturing an in-sample Sharpe.
#:
#: `swing_lookback` and `momentum_window` are the two the premise actually
#: rests on - how much structure a pivot needs, and how long a pivot stays
#: relevant - so they carry the sweep. `use_macro_trend` is swept because the
#: request declared the Heiken Ashi ribbon as a filter without saying what it
#: costs; the sweep answers whether it earns its place rather than that being
#: decided by whoever wrote the module.
#:
#: `rsi_oversold`/`rsi_overbought` are pinned at the request's 30/70 and NOT
#: swept: they are the definition of "leaving an extreme", and sweeping them
#: alongside the window would let the grid find a threshold that fits the
#: in-sample tape rather than a momentum event.
PARAM_GRID = {
    "swing_lookback": [8, 12, 20],
    "momentum_window": [5, 10, 15],
    "sl_atr_mult": [1.5, 2.0],
    "use_macro_trend": [True, False],
}

LOGIC = {
    "concept": (
        "A trend resumes from a structural pivot, not from an arbitrary bar. "
        "A Semafor swing over {swing_lookback} bars marks the pivot, RSI"
        "({rsi_period}) leaving an extreme says momentum re-engaged after it, "
        "and a close crossing EMA({fast_ema}) is the bar to act on; the "
        "smoothed Heiken Ashi ribbon over EMA({ha_period})/EMA({ha_smooth}) "
        "refuses the setups that form against the macro lean. The pivot is "
        "CONFIRMED {swing_lookback} bars after it forms, never read centred, "
        "so no signal depends on a bar that had not printed. Trades are "
        "attributed by their ENTRY bar, never the exit, so a move opened in "
        "one quadrant that runs into another still scores where it opened."),
    "entry": (
        "LONG when Close crosses ABOVE EMA({fast_ema}), a swing LOW was "
        "confirmed within the last {momentum_window} bars, and RSI"
        "({rsi_period}) crossed above {rsi_oversold} at or after that pivot. "
        "SHORT when Close crosses BELOW EMA({fast_ema}), a swing HIGH was "
        "confirmed within {momentum_window} bars, and RSI crossed below "
        "{rsi_overbought} at or after it. With use_macro_trend the long side "
        "additionally needs the smoothed Heiken Ashi candle green and rising "
        "under the close, and the short side its mirror."),
    "exit": (
        "The opposite trigger always closes the position. With "
        "use_midline_exit={use_midline_exit} a close crossing back through "
        "EMA({fast_ema}) closes it too, and with "
        "use_rsi_zone_exit={use_rsi_zone_exit} so does RSI entering the "
        "opposite extreme - {rsi_overbought} for a long, {rsi_oversold} for a "
        "short. A protective stop at {sl_atr_mult} x ATR(14) sits underneath "
        "all of them, trailing={trailing}. No ATR take-profit is modelled "
        "(tp_atr_mult={tp_atr_mult}): the RSI zone is the target and it is a "
        "SIGNAL, because the engine has no target orders."),
}


# ---------------------------------------------------------------------------
# Indicator kernels
#
# `_ema`, `_wilder`, `_true_range`, `_atr`, `_as_series`, `_cross_above`,
# `_cross_below` and `_walk_loop` below are DUPLICATED VERBATIM from
# `dbb_momentum_breakout_20260909.py`, which shares them with the rest of this
# directory. Strategy modules are loaded from a FILE PATH by
# `agents.tier3_workers.load_strategy` and promoted as a self-contained copy,
# so a shared import would resolve against whatever happens to sit beside the
# module at load time - and a promoted package must reproduce the file that
# was certified, byte for byte. Do not "improve" one alone.
# ---------------------------------------------------------------------------
def _ema(series: pd.Series, period: int) -> pd.Series:
    """
    A span-`period` exponential mean, NaN until `period` bars exist.

    `min_periods=period` rather than pandas' default of 1: without it the
    first bar's EMA is that bar's own close, which is not an average of
    anything, and a ribbon built from it leans wherever the first bar happened
    to sit.
    """
    return series.ewm(span=period, adjust=False, min_periods=period).mean()


def _wilder(series: pd.Series, period: int) -> pd.Series:
    """
    Wilder's smoothing - the average the ATR and the RSI are actually defined
    on.

    `alpha = 1/period` with `adjust=False` is Wilder's recursion exactly. A
    span-`period` EMA (`_ema` above) is a different, roughly twice as fast,
    average, and using it here would produce an "ATR(14)" and an "RSI(14)"
    that no other tool agrees with - so a reader checking a stop distance or
    an oversold reading against their own chart would see it somewhere else.
    """
    return series.ewm(alpha=1.0 / period, adjust=False,
                      min_periods=period).mean()


def _true_range(bars: pd.DataFrame) -> pd.Series:
    """
    True range per bar.

    `.shift(1)` looks one bar BACKWARD, which is the correct direction: the
    true range at bar i uses bar i-1's close and nothing later.
    """
    high, low, close = bars["high"], bars["low"], bars["close"]
    prev = close.shift(1)
    return pd.concat([(high - low).abs(),
                      (high - prev).abs(),
                      (low - prev).abs()], axis=1).max(axis=1)


def _atr(bars: pd.DataFrame, period: int = ATR_PERIOD) -> pd.Series:
    """
    True range, Wilder-smoothed. NaN until `period` bars exist.

    A ZERO ATR IS A MEASUREMENT, NOT A GAP, and it is left as the 0.0 it is.
    A window in which nothing moved - a halted contract, a dead overnight
    hour - has a true ATR of zero. `signal_fn` refuses to enter on such a bar
    rather than placing a bracket of zero width around the fill.
    """
    return _wilder(_true_range(bars), period)


def _as_series(value, index) -> pd.Series:
    """A scalar level as a Series on `index`; a Series is returned as-is."""
    if isinstance(value, pd.Series):
        return value
    return pd.Series(float(value), index=index)


def _cross_above(fast: pd.Series, level) -> pd.Series:
    """
    True on the bar `fast` crosses UP through `level` - a series or a scalar.

        fast[i] > level[i]  AND  fast[i-1] <= level[i-1]

    A STATE (`fast > level`) would be true for every bar of a run; this is the
    EVENT, true once. `<=` on the previous bar rather than `<` so a pair that
    was exactly equal and then separated counts as a cross - with two
    oscillators quantised by the same price series, exact equality is not the
    measure-zero event it is for two continuous curves.

    NaN-SAFE BY CONSTRUCTION: every comparison against NaN is False, so a
    warm-up bar is never a cross. `.shift(1)` looks one bar BACKWARD.
    """
    other = _as_series(level, fast.index)
    return (fast > other) & (fast.shift(1) <= other.shift(1))


def _cross_below(fast: pd.Series, level) -> pd.Series:
    """
    True on the bar `fast` crosses DOWN through `level`. The exact mirror of
    `_cross_above`, written out rather than expressed as its negation:
    `~_cross_above` is true on every bar that merely fails to be a cross up,
    which is almost all of them.
    """
    other = _as_series(level, fast.index)
    return (fast < other) & (fast.shift(1) >= other.shift(1))


def _rsi(close: pd.Series, period: int) -> pd.Series:
    """
    Wilder's RSI. NaN until `period` bars of change exist.

    Wilder-smoothed gains and losses, not a simple mean of them: the simple
    form is a different oscillator that crosses 30 on different bars, and this
    module's entire momentum gate is a threshold cross.

    A zero average loss gives RSI 100 rather than a division by zero - a
    window with no down bar is a real state, not a gap - and is produced here
    by letting the division yield `inf` and mapping it, rather than by a
    branch that would have to be repeated for the short side.
    """
    delta = close.diff()
    gain = delta.clip(lower=0.0)
    loss = (-delta).clip(lower=0.0)
    avg_gain = _wilder(gain, period)
    avg_loss = _wilder(loss, period)
    rs = avg_gain / avg_loss.replace(0.0, np.nan)
    rsi = 100.0 - (100.0 / (1.0 + rs))
    # An all-gain window: avg_loss is 0, rs is NaN by the replace above, and
    # the honest reading is 100 - fully overbought - not "unknown".
    return rsi.where(~((avg_loss == 0.0) & (avg_gain > 0.0)), 100.0)


def _heiken_ashi_smoothed(bars: pd.DataFrame, period: int, smooth: int
                          ) -> dict[str, pd.Series]:
    """
    The smoothed Heiken Ashi ribbon: EMA the raw OHLC, build Heiken Ashi on
    the result, then EMA the HA candles.

    THE HA OPEN IS A RECURRENCE, AND IT IS COMPUTED AS ONE.

        HA_open[i] = (HA_open[i-1] + HA_close[i-1]) / 2

    which is exactly an EWM with `alpha=HA_OPEN_ALPHA` over `HA_close` shifted
    one bar - `y[i] = a*x[i] + (1-a)*y[i-1]` with `x[i] = HA_close[i-1]` and
    `a = 0.5`. Written that way rather than as a Python loop because it is
    vectorised and identical, not as an approximation of it.

    The one difference from the textbook form is the SEED: the textbook sets
    `HA_open[0] = (open[0] + close[0]) / 2` and this seeds at the first valid
    `HA_close`. The two converge by a factor of 2 per bar, so by the end of
    the `period` warm-up they differ by about 2^-period - and every bar of
    that warm-up is masked out of the signals anyway. Recorded because a
    reader comparing this ribbon against a charting package bar by bar will
    see it, and should know it is the seed and not the rule.

    Nothing here reads a bar later than i.
    """
    o = _ema(bars["open"].astype("float64"), period)
    h = _ema(bars["high"].astype("float64"), period)
    l = _ema(bars["low"].astype("float64"), period)      # noqa: E741
    c = _ema(bars["close"].astype("float64"), period)

    ha_close = (o + h + l + c) / 4.0
    ha_open = ha_close.shift(1).ewm(alpha=HA_OPEN_ALPHA, adjust=False).mean()
    ha_high = pd.concat([h, ha_open, ha_close], axis=1).max(axis=1)
    ha_low = pd.concat([l, ha_open, ha_close], axis=1).min(axis=1)

    return {
        "ha_open": _ema(ha_open, smooth),
        "ha_high": _ema(ha_high, smooth),
        "ha_low": _ema(ha_low, smooth),
        "ha_close": _ema(ha_close, smooth),
    }


def _swing_points(bars: pd.DataFrame, lookback: int
                  ) -> tuple[pd.Series, pd.Series]:
    """
    Semafor pivots, CONFIRMED rather than centred. Returns
    `(swing_low_confirmed, swing_high_confirmed)`, both True on the bar the
    pivot becomes knowable.

    THIS IS THE FUNCTION THAT DECIDES WHETHER THIS MODULE REPAINTS. A Semafor
    marks a swing low at bar `p` when `low[p]` is the lowest of the `lookback`
    bars on EITHER side of it. The right-hand side has not printed at bar `p`,
    so the arrow appears `lookback` bars later and every bar in between can
    erase it. A backtest that reads the centred mask at bar `p` buys the exact
    bottom of every leg and reports a curve nothing can reproduce live.

    Here the window is `2*lookback + 1` bars ending at bar i, the pivot sits
    at its CENTRE - bar `i - lookback` - and the mask is True at bar i. So a
    signal on bar i reads bars `i - 2*lookback .. i` and nothing later, and
    the entry is late by `lookback` bars relative to the drawn arrow, exactly
    as it would be live.

    `.rolling(...).min()` over the trailing window plus a `.shift(-lookback)`
    would be the same arithmetic and would be WRONG: a negative shift reads
    forward. The window is built trailing and the pivot is indexed backward
    inside it, so no negative shift appears anywhere in this module.

    Ties go to a pivot. `<=` against the window minimum admits a double
    bottom, which is a real structure; requiring a strict minimum would drop
    the flat-based ones entirely.
    """
    window = 2 * int(lookback) + 1
    low = bars["low"].astype("float64")
    high = bars["high"].astype("float64")

    win_min = low.rolling(window, min_periods=window).min()
    win_max = high.rolling(window, min_periods=window).max()

    # The candidate pivot is the CENTRE of the trailing window: `lookback`
    # bars back from the bar doing the confirming. `.shift(lookback)` is a
    # positive shift and looks BACKWARD.
    pivot_low = low.shift(int(lookback))
    pivot_high = high.shift(int(lookback))

    return (pivot_low <= win_min).fillna(False), \
           (pivot_high >= win_max).fillna(False)


def _bars_since(mask: pd.Series) -> np.ndarray:
    """
    Bars elapsed since `mask` was last True, as a float array; `inf` before
    the first True.

    Vectorised through a running maximum of the positions where the mask
    fired, rather than a Python loop: `np.maximum.accumulate` over
    `where(mask, i, -1)` carries the most recent hit forward, which is the
    same answer a loop would give and is what makes the ordering test in
    `_layers` a comparison of two arrays instead of a second walk.

    `inf` rather than a large integer for "never": every comparison against it
    is False, so a window test needs no separate has-fired branch.
    """
    idx = np.arange(len(mask), dtype="float64")
    hit = np.where(mask.to_numpy(dtype=bool), idx, -np.inf)
    last = np.maximum.accumulate(hit)
    return idx - last


def _walk_loop(long_entry_ok: np.ndarray,
               short_entry_ok: np.ndarray,
               long_sig_exit: np.ndarray,
               short_sig_exit: np.ndarray,
               open_: np.ndarray,
               high: np.ndarray,
               low: np.ndarray,
               atr: np.ndarray,
               flat_bar: np.ndarray,
               sl_mult: float,
               tp_mult: float,
               trailing: bool) -> tuple[np.ndarray, np.ndarray,
                                        np.ndarray, np.ndarray,
                                        np.ndarray, np.ndarray]:
    """
    THREE-state machine over the bars: flat, long, or short - each side under
    its own stop, target and signal exit.

    DUPLICATED VERBATIM from `dbb_momentum_breakout_20260909.py`, which shares
    it with `keltner_trend_drift_20260901.py`,
    `sma_momentum_crossover_20260818.py`, `t3_braid_scalp_20260823.py` and
    `ema_crossover_20260821.py`, by the same convention that duplicates
    `_wilder` and `_atr` across this directory. Do not "improve" one alone.

    The timeline matches the engine's. An entry signal on bar i is filled at
    bar i+1's open, so the position is live from bar i+1, the fill price is
    `open_[i + 1]`, and the extreme-price mark starts there - NOT on the
    signal bar. Both distances are frozen at `mult * ATR` as measured on the
    SIGNAL bar and never re-measured as volatility changes.

    The two sides, written out rather than folded into a sign flip, because a
    reader has to be able to check them against the specification by eye:

        LONG    stop     fill - dist    trailing: (highest high since fill) - dist
                target   fill + dist
                exits    low  <= stop   or  high >= target
        SHORT   stop     fill + dist    trailing: (lowest low   since fill) + dist
                target   fill - dist
                exits    high >= stop   or  low  <= target

    A short stop placed BELOW the fill would be breached by the fill bar
    itself; this is the reason the sides are not a sign flip.

    `tp_mult` is NaN when no take-profit is modelled, rather than a sentinel
    like 0 or a huge number. NaN propagates into `target` and every comparison
    against it is False, so the target simply never fires on either side.

    A bar carrying BOTH a long and a short entry signal while flat takes
    NEITHER, matching `backtest.engine._clean_signals_ls_loop`. A well-formed
    strategy cannot produce it - price cannot cross above and below the same
    EMA on one bar - so the branch exists to make a malformed one visible as a
    missing trade rather than a plausible one-sided curve.

    A position is never reversed directly. The walk enters only from flat, so
    a short signal arriving while long is ignored; the long must exit first.

    Exits are checked from the fill bar onward, never on the signal bar.
    """
    n = long_entry_ok.shape[0]
    long_entries = np.zeros(n, dtype=np.bool_)
    long_exits = np.zeros(n, dtype=np.bool_)
    short_entries = np.zeros(n, dtype=np.bool_)
    short_exits = np.zeros(n, dtype=np.bool_)
    stop_level = np.full(n, np.nan)
    tp_level = np.full(n, np.nan)

    state = 0                            # 0 flat, 1 long, -1 short
    fill_i = 0
    stop_dist = 0.0
    tp_dist = np.nan
    entry_px = np.nan
    hw = 0.0                             # highest high since the fill (long)
    lw = 0.0                             # lowest low since the fill (short)

    for i in range(n):
        if state == 0:
            go_long = long_entry_ok[i]
            go_short = short_entry_ok[i]
            if go_long and go_short:
                continue                 # ambiguous bar: take neither side
            if go_long or go_short:
                fill_i = i + 1
                stop_dist = sl_mult * atr[i]
                # NaN in, NaN out: no take-profit stays no take-profit.
                tp_dist = tp_mult * atr[i]
                entry_px = np.nan
                hw = -np.inf
                lw = np.inf
                if go_long:
                    long_entries[i] = True
                    state = 1
                else:
                    short_entries[i] = True
                    state = -1
            continue

        if i < fill_i:
            continue

        if i == fill_i:
            # The engine's own fill: the open of the bar AFTER the signal. Not
            # the signal bar's close, which the position never traded at.
            entry_px = open_[i]

        if state == 1:
            if trailing:
                if high[i] > hw:
                    hw = high[i]
                level = hw - stop_dist
            else:
                level = entry_px - stop_dist

            target = entry_px + tp_dist   # NaN when no target is modelled
            stop_level[i] = level
            tp_level[i] = target

            hit_stop = low[i] <= level
            # False whenever `target` is NaN, which is how "no take-profit" is
            # expressed. Every comparison against NaN is False in both numba
            # and numpy, so the interpreted fallback cannot disagree with the
            # compiled loop about it.
            hit_tp = high[i] >= target

            # A bar that breaches both produces one exit on this bar either
            # way, and the engine fills it at the next bar's open regardless -
            # so the intrabar race between the stop and the target is not
            # resolved here because it cannot change the result.
            if hit_stop or hit_tp or long_sig_exit[i] or flat_bar[i]:
                long_exits[i] = True
                state = 0
        else:
            if trailing:
                if low[i] < lw:
                    lw = low[i]
                level = lw + stop_dist
            else:
                level = entry_px + stop_dist

            target = entry_px - tp_dist   # NaN when no target is modelled
            stop_level[i] = level
            tp_level[i] = target

            hit_stop = high[i] >= level
            hit_tp = low[i] <= target     # False when target is NaN

            if hit_stop or hit_tp or short_sig_exit[i] or flat_bar[i]:
                short_exits[i] = True
                state = 0

    return (long_entries, long_exits, short_entries, short_exits,
            stop_level, tp_level)


try:                                    # pragma: no cover - env dependent
    from numba import njit

    # No `cache=True`. `load_strategy` imports this module from a file path,
    # so it is not importable by name. Compiling still works and numba writes
    # the cache; it is the LOAD in a later process that fails, with
    # `ModuleNotFoundError: No module named '<dynamic>'`, which is why the
    # first run after a cache wipe looks clean and the second one dies.
    _walk = njit(nogil=True)(_walk_loop)
except ImportError:                     # pragma: no cover - env dependent
    # Same function, interpreted. `backtest.engine.clean_signals` degrades the
    # same way, and the fallback has to exist because a missing compiler must
    # not change which trades a strategy takes.
    _walk = _walk_loop


# --------------------------------------------------------------------------
# Validation
# --------------------------------------------------------------------------
def _validate(ha_period: int, ha_smooth: int, swing_lookback: int,
              fast_ema: int, rsi_period: int, rsi_oversold: float,
              rsi_overbought: float, momentum_window: int,
              sl_atr_mult: float, tp_atr_mult: float | None,
              trailing: bool) -> None:
    """
    Refuse a parameter set that cannot mean what it says, where it is passed
    rather than as a strange equity curve. Each has a specific failure behind
    it:

    * A period below 2 makes its average the series itself, and every ribbon
      and oscillator collapses onto price.
    * `swing_lookback < 1` leaves no bars either side of the pivot, so every
      bar is trivially its own swing high AND its own swing low.
    * `rsi_oversold >= rsi_overbought` inverts the momentum gate: the long
      side would demand a cross up through a level ABOVE the short side's, and
      `use_rsi_zone_exit` would close a position on the bar that opened it.
    * `momentum_window < 1` means the pivot and the RSI cross must land on the
      same bar, which is not the hypothesis and fires almost never.
    * A stop inside MIN_STOP_ATR_MULT sits inside the bar's own noise.
    * `tp_atr_mult` may be None - that IS a setting, meaning "no target" - but
      a non-positive number would put the target at or behind the fill and
      close every trade on its first bar.
    """
    for name, value in (("ha_period", ha_period), ("ha_smooth", ha_smooth),
                        ("fast_ema", fast_ema), ("rsi_period", rsi_period)):
        if int(value) < 2:
            raise ValueError(
                f"{name} must be >= 2; got {value!r}. Below that the average "
                f"is the series itself and the indicator collapses onto "
                f"price.")
    if int(swing_lookback) < 1:
        raise ValueError(
            f"swing_lookback must be >= 1; got {swing_lookback!r}. With no "
            f"bars either side every bar is trivially its own swing high and "
            f"its own swing low.")
    if int(momentum_window) < 1:
        raise ValueError(
            f"momentum_window must be >= 1; got {momentum_window!r}. Below "
            f"that the pivot and the RSI cross must land on the same bar, "
            f"which is not the rule this module implements.")
    if not 0.0 < float(rsi_oversold) < float(rsi_overbought) < 100.0:
        raise ValueError(
            f"need 0 < rsi_oversold < rsi_overbought < 100; got "
            f"{rsi_oversold!r} and {rsi_overbought!r}. Inverted, the long "
            f"gate demands a cross through a level above the short gate's and "
            f"use_rsi_zone_exit closes a position on the bar that opened it.")
    if float(sl_atr_mult) < MIN_STOP_ATR_MULT:
        raise ValueError(
            f"sl_atr_mult must be >= {MIN_STOP_ATR_MULT}; got "
            f"{sl_atr_mult!r}. A tighter stop sits inside the bar's own noise "
            f"and the run measures the cost model.")
    if tp_atr_mult is not None and float(tp_atr_mult) <= 0.0:
        raise ValueError(
            f"tp_atr_mult must be > 0 or None (no target); got "
            f"{tp_atr_mult!r}. At or below zero the target sits at or behind "
            f"the fill and every trade closes on its first bar.")
    if not isinstance(trailing, (bool, np.bool_)):
        raise ValueError(f"trailing must be a bool; got {trailing!r}")


def _tp_distance(tp_atr_mult: float | None) -> float:
    """
    The take-profit multiple as the walk wants it: NaN for "no target".

    NaN rather than 0 or a large sentinel, because every comparison against
    NaN is False in both the compiled and the interpreted loop - so the target
    never fires and the drawn line is a visible gap.
    """
    if tp_atr_mult is None:
        return float("nan")
    return float(tp_atr_mult)


# --------------------------------------------------------------------------
# Layers
# --------------------------------------------------------------------------
def _layers(bars: pd.DataFrame, ha_period: int, ha_smooth: int,
            swing_lookback: int, fast_ema: int, rsi_period: int,
            rsi_oversold: float, rsi_overbought: float,
            momentum_window: int, use_macro_trend: bool,
            use_midline_exit: bool, use_rsi_zone_exit: bool
            ) -> dict[str, pd.Series]:
    """
    Every series both `signal_fn` and `indicators` read, computed ONCE.

    One call site for the maths is the point: a second implementation in the
    report would be free to disagree with this one and draw a cross a bar from
    where the trade fired, with nothing raising.

    The toggles live here rather than in `signal_fn` so a disabled filter is a
    Series of True with the underlying series still computed and still drawn -
    a reader can see what the filter WOULD have said on a run where it was off.
    """
    close = bars["close"].astype("float64")
    HA = _heiken_ashi_smoothed(bars, int(ha_period), int(ha_smooth))
    ema_fast = _ema(close, int(fast_ema))
    rsi = _rsi(close, int(rsi_period))
    atr = _atr(bars, ATR_PERIOD)

    # THE MACRO LEAN. Three conditions, all from the request: price above the
    # ribbon, the HA candle green, and the ribbon itself rising. `.diff()`
    # looks one bar BACKWARD.
    ha_green = HA["ha_close"] > HA["ha_open"]
    ha_rising = HA["ha_close"].diff() > 0.0
    macro_long = (close > HA["ha_close"]) & ha_green & ha_rising
    macro_short = (close < HA["ha_close"]) & (~ha_green) & (
        HA["ha_close"].diff() < 0.0)
    if not use_macro_trend:
        macro_long = pd.Series(True, index=bars.index)
        macro_short = pd.Series(True, index=bars.index)

    # THE PIVOTS, confirmed rather than centred - see `_swing_points`.
    swing_low, swing_high = _swing_points(bars, int(swing_lookback))

    # THE MOMENTUM GATE, AND THE TWO CLOCKS IT HAS TO KEEP APART.
    #
    # `_swing_points` returns the bar a pivot is CONFIRMED on, which is
    # `swing_lookback` bars after the pivot itself. So there are two ages for
    # one pivot and they differ by exactly that lag:
    #
    #     since_low            bars since the pivot became KNOWN
    #     since_low + lookback bars since the low actually PRINTED
    #
    # The request's rule is "RSI crossing above 30 within a rolling window
    # after a swing low" - after the LOW, not after the news of it. RSI
    # typically recrosses 30 while the pivot is still being confirmed, so
    # testing the cross against the confirmation bar demands it be MORE recent
    # than the confirmation and the gate never opens. That is not a
    # conservative version of the rule, it is a different one that produces
    # zero trades on a tape full of the setup, and it is what the first
    # implementation here did.
    #
    # So: the pivot must be freshly ACTIONABLE (confirmed within the window,
    # which is the only clock a live system has), and the RSI cross must have
    # landed at or after the low PRINTED. `inf` before either has ever fired
    # makes every comparison False, so no has-fired branch is needed.
    rsi_up = _cross_above(rsi, float(rsi_oversold))
    rsi_down = _cross_below(rsi, float(rsi_overbought))
    lag = float(int(swing_lookback))
    since_low = _bars_since(swing_low)
    since_high = _bars_since(swing_high)
    since_rsi_up = _bars_since(rsi_up)
    since_rsi_down = _bars_since(rsi_down)
    w = float(momentum_window)
    gate_long = pd.Series(
        (since_low <= w) & (since_rsi_up <= since_low + lag),
        index=bars.index)
    gate_short = pd.Series(
        (since_high <= w) & (since_rsi_down <= since_high + lag),
        index=bars.index)

    # THE TRIGGER IS A CROSS, NOT A STATE. A run of bars already above the
    # fast EMA is not a fresh trigger - the trigger was the bar that got
    # there - and a state test would fire an entry on every one of them.
    cross_up = _cross_above(close, ema_fast)
    cross_down = _cross_below(close, ema_fast)

    trigger_long = cross_up & gate_long & macro_long
    trigger_short = cross_down & gate_short & macro_short

    # THE EXITS. The opposite trigger is unconditional: a setup that has
    # reversed is not a position to keep holding. The other two are the
    # request's two risk configurations and are toggles.
    exit_long = trigger_short.copy()
    exit_short = trigger_long.copy()
    if use_midline_exit:
        exit_long = exit_long | cross_down
        exit_short = exit_short | cross_up
    if use_rsi_zone_exit:
        # The request's "RSI opposite zone take-profit". A SIGNAL, not a
        # bracket - the engine has no target orders, so it is detected on the
        # bar that reaches the zone and filled at the next bar's open.
        exit_long = exit_long | _cross_above(rsi, float(rsi_overbought))
        exit_short = exit_short | _cross_below(rsi, float(rsi_oversold))

    return {
        "close": close, "ema_fast": ema_fast, "rsi": rsi, "atr": atr,
        "ha_open": HA["ha_open"], "ha_high": HA["ha_high"],
        "ha_low": HA["ha_low"], "ha_close": HA["ha_close"],
        "ha_green": ha_green, "ha_rising": ha_rising,
        "macro_long": macro_long, "macro_short": macro_short,
        "swing_low": swing_low, "swing_high": swing_high,
        "rsi_up": rsi_up, "rsi_down": rsi_down,
        "gate_long": gate_long, "gate_short": gate_short,
        "cross_up": cross_up, "cross_down": cross_down,
        "trigger_long": trigger_long, "trigger_short": trigger_short,
        "exit_long": exit_long, "exit_short": exit_short,
        "dist_ema_atr": (close - ema_fast) / atr.replace(0.0, np.nan),
        "dist_ha_atr": (close - HA["ha_close"]) / atr.replace(0.0, np.nan),
    }


# --------------------------------------------------------------------------
# The contract functions
# --------------------------------------------------------------------------
def signal_fn(bars: pd.DataFrame,
              ha_period: int = 20,
              ha_smooth: int = 5,
              swing_lookback: int = 12,
              fast_ema: int = 9,
              rsi_period: int = 14,
              rsi_oversold: float = 30.0,
              rsi_overbought: float = 70.0,
              momentum_window: int = 10,
              use_macro_trend: bool = True,
              use_midline_exit: bool = True,
              use_rsi_zone_exit: bool = False,
              sl_atr_mult: float = 2.0,
              tp_atr_mult: float | None = None,
              trailing: bool = False) -> tuple[pd.Series, pd.Series,
                                               pd.Series, pd.Series]:
    """
    Returns the FOUR-MASK form: (long_entries, long_exits, short_entries,
    short_exits), all boolean Series on `bars.index`.

    A three-tuple or a bare Series RAISES in `engine.unpack_signals` rather
    than silently losing the short side into a plausible long-only curve.

    THE SHORT SIDE IS NOT THE LONG SIDE WITH A SIGN FLIP. Inside `_walk_loop`
    the short stop sits ABOVE the fill; placed below it, the fill bar itself
    would breach it. The masks are written out per side for the same reason.

    NOTHING HERE READS A BAR LATER THAN i. The Semafor pivot is confirmed
    `swing_lookback` bars after it forms rather than read centred, and no
    negative shift appears anywhere in this module.
    """
    _validate(ha_period, ha_smooth, swing_lookback, fast_ema, rsi_period,
              rsi_oversold, rsi_overbought, momentum_window, sl_atr_mult,
              tp_atr_mult, trailing)

    L = _layers(bars, int(ha_period), int(ha_smooth), int(swing_lookback),
                int(fast_ema), int(rsi_period), float(rsi_oversold),
                float(rsi_overbought), int(momentum_window),
                bool(use_macro_trend), bool(use_midline_exit),
                bool(use_rsi_zone_exit))

    long_ok = L["trigger_long"].fillna(False).to_numpy()
    short_ok = L["trigger_short"].fillna(False).to_numpy()
    long_sig_exit = L["exit_long"].fillna(False).to_numpy()
    short_sig_exit = L["exit_short"].fillna(False).to_numpy()

    atr = L["atr"].to_numpy(dtype="float64")
    # A bar with no ATR yet is not tradable: the protective bracket has no
    # width, and admitting it would place a stop at the fill price.
    warm = ~np.isfinite(atr) | (atr <= 0.0)
    # The ribbon warms up on a longer window than the ATR - EMA(ha_period)
    # then EMA(ha_smooth) on top of it - and a NaN ribbon makes the macro gate
    # False anyway. Masking it explicitly keeps that true when
    # `use_macro_trend` is off, where the ribbon is not in the gate at all.
    warm = warm | ~np.isfinite(L["ha_close"].to_numpy(dtype="float64"))
    warm = warm | ~np.isfinite(L["ema_fast"].to_numpy(dtype="float64"))
    long_ok = long_ok & ~warm
    short_ok = short_ok & ~warm

    flat_bar = np.zeros(len(bars), dtype=bool)

    le, lx, se, sx, _, _ = _walk(
        long_ok, short_ok, long_sig_exit, short_sig_exit,
        bars["open"].to_numpy(dtype="float64"),
        bars["high"].to_numpy(dtype="float64"),
        bars["low"].to_numpy(dtype="float64"),
        np.nan_to_num(atr, nan=0.0), flat_bar, float(sl_atr_mult),
        _tp_distance(tp_atr_mult), bool(trailing))

    idx = bars.index
    return (pd.Series(le, index=idx), pd.Series(lx, index=idx),
            pd.Series(se, index=idx), pd.Series(sx, index=idx))


def generate_signals(df: pd.DataFrame, params: dict | None = None
                     ) -> tuple[pd.Series, pd.Series, pd.Series, pd.Series]:
    """
    The `generate_signals(df, params)` calling convention, as a thin adapter.

    NOT THE ENGINE'S ENTRY POINT. `agents.tier3_workers.load_strategy` binds
    `make_signal_fn(**params)` or `signal_fn(bars, **params)` and knows
    nothing about this name. It delegates rather than reimplementing, so the
    two can never disagree about what a signal is.
    """
    bound = {**DEFAULT_PARAMS, **(params or {})}
    unknown = set(bound) - set(DEFAULT_PARAMS)
    if unknown:
        raise ValueError(f"unknown parameter(s): {sorted(unknown)}")
    return signal_fn(df, **bound)


def indicators(bars: pd.DataFrame, **params) -> dict[str, pd.Series]:
    """
    Full-length series drawn over the trade inspector's candles, from the same
    `_layers` call `signal_fn` uses - so the chart cannot draw a cross a bar
    from where the entry actually happened.
    """
    p = {**DEFAULT_PARAMS, **(params or {})}
    L = _layers(bars, int(p["ha_period"]), int(p["ha_smooth"]),
                int(p["swing_lookback"]), int(p["fast_ema"]),
                int(p["rsi_period"]), float(p["rsi_oversold"]),
                float(p["rsi_overbought"]), int(p["momentum_window"]),
                bool(p["use_macro_trend"]), bool(p["use_midline_exit"]),
                bool(p["use_rsi_zone_exit"]))
    return {
        f"HA Smoothed({int(p['ha_period'])}/{int(p['ha_smooth'])})":
            L["ha_close"],
        "HA Open": L["ha_open"],
        f"EMA({int(p['fast_ema'])})": L["ema_fast"],
        f"RSI({int(p['rsi_period'])})": L["rsi"],
        f"ATR({ATR_PERIOD})": L["atr"],
    }


def ml_features(bars: pd.DataFrame, **params) -> pd.DataFrame:
    """
    The matrix Version B's classifier is fitted on: one row per bar, in order.

    CAUSALITY IS THIS MODULE'S RESPONSIBILITY. Every column is built from
    `_layers`, which reads only bars <= i, and nothing is scaled against the
    whole frame - a scaler fitted end to end leaks the test period's
    distribution into the training rows without tripping any shift-based
    audit.

    SHAPE IS CHECKED BY THE CALLER AND A FAILURE RAISES - unlike `indicators`,
    which is wrapped, because a broken chart annotation must not throw away a
    completed backtest but a silently swapped feature matrix must not survive
    one.

    The columns are the state the RULES read, as RATIOS rather than levels. A
    distance of 12.5 points means nothing across contracts, and a classifier
    fitted on levels learns the symbol rather than the setup. `bars_since` is
    clipped rather than left at `inf`: an unbounded column is not a feature, it
    is a switch that saturates the split.
    """
    p = {**DEFAULT_PARAMS, **(params or {})}
    L = _layers(bars, int(p["ha_period"]), int(p["ha_smooth"]),
                int(p["swing_lookback"]), int(p["fast_ema"]),
                int(p["rsi_period"]), float(p["rsi_oversold"]),
                float(p["rsi_overbought"]), int(p["momentum_window"]),
                bool(p["use_macro_trend"]), bool(p["use_midline_exit"]),
                bool(p["use_rsi_zone_exit"]))
    close = L["close"]
    atr = L["atr"].replace(0.0, np.nan)
    cap = float(4 * int(p["momentum_window"]))
    volume = (bars["volume"].astype("float64") if "volume" in bars.columns
              else pd.Series(np.nan, index=bars.index))
    vol_sma = volume.rolling(20, min_periods=20).mean().shift(1)
    vol_std = volume.rolling(20, min_periods=20).std().shift(1)
    out = pd.DataFrame({
        "rsi": L["rsi"],
        "dist_ema_atr": L["dist_ema_atr"],
        "dist_ha_atr": L["dist_ha_atr"],
        "ha_body_atr": (L["ha_close"] - L["ha_open"]) / atr,
        "ha_slope_atr": L["ha_close"].diff() / atr,
        "bars_since_swing_low": np.minimum(_bars_since(L["swing_low"]), cap),
        "bars_since_swing_high": np.minimum(_bars_since(L["swing_high"]), cap),
        "bars_since_rsi_up": np.minimum(_bars_since(L["rsi_up"]), cap),
        "bars_since_rsi_down": np.minimum(_bars_since(L["rsi_down"]), cap),
        "norm_atr": atr / close,
        "roc_3": close.pct_change(3),
        "roc_10": close.pct_change(10),
        "range_atr": (bars["high"] - bars["low"]) / atr,
        "volume_z": (volume - vol_sma) / vol_std.replace(0.0, np.nan),
    }, index=bars.index)
    return out.replace([np.inf, -np.inf], np.nan).fillna(0.0)


def make_signal_fn(**params):
    """The parameterised form `load_strategy` prefers. Binds `params` once and
    returns the one-argument callable the engine walks."""
    bound = {**DEFAULT_PARAMS, **(params or {})}
    unknown = set(bound) - set(DEFAULT_PARAMS)
    if unknown:
        # Raise rather than ignore. A stale grid key silently dropped would
        # sweep the DEFAULT and report it under the swept name.
        raise ValueError(f"unknown parameter(s): {sorted(unknown)}")

    def _fn(bars: pd.DataFrame):
        return signal_fn(bars, **bound)
    return _fn
