"""
campaign NQ 20260814 - Auto-staged for campaign: Run a complete quantitative backtest and validation campaign for a volatility-adjusted 20-period Donchian channel breako

Generated by agents.tier3_workers.generate_strategy_boilerplate on 2026-08-14.

THIS IS A TEMPLATE. The signal logic below is a placeholder and must be
replaced before the result of any backtest over it means anything.

The streaming interface
-----------------------
`signal_fn` receives ONE symbol's bars and returns two boolean Series aligned
to them. It never sees more than one instrument, which is deliberate: the
engine used to accept a multi-symbol frame, and a `close.rolling(200).mean()`
over it averaged across 27 unrelated contracts without raising.

Rules for anything written here:

  - No data access. The engine reads the bars and hands them over.
  - No cost handling. Slippage and commission live in BacktestConfig.
  - No session logic. flat_by_close and the Sunday merge are handled upstream.
  - No lookahead. Anything derived from bar i must use data up to i only;
    the engine fills at the NEXT bar's open.
"""

from __future__ import annotations

import pandas as pd

TIMEFRAME = "1m"
SYMBOLS = ['NQ']
DEFAULT_PARAMS = {'fast': 20, 'slow': 50}


def make_signal_fn(fast: int = 20, slow: int = 50):
    """Bind parameters and return the signal function the engine calls."""
    if not isinstance(fast, (int, float)) or fast <= 0:
        raise ValueError(f"fast must be positive, got {fast!r}")
    if not isinstance(slow, (int, float)) or slow <= 0:
        raise ValueError(f"slow must be positive, got {slow!r}")

    def signal_fn(bars: pd.DataFrame) -> tuple[pd.Series, pd.Series]:
        close = bars["close"]

        # ------------------------------------------------------------------
        # PLACEHOLDER LOGIC - replace this.
        # Written as a trivially inspectable crossover so a first run
        # exercises the plumbing without pretending to be a strategy.
        #
        # Note the _ma suffixes: assigning to the parameter name here would
        # make it a local of signal_fn and shadow the closure, raising
        # UnboundLocalError on the first call.
        # ------------------------------------------------------------------
        fast_ma = close.rolling(fast, min_periods=fast).mean()
        slow_ma = close.rolling(slow, min_periods=slow).mean()

        entries = (fast_ma > slow_ma) & (fast_ma.shift(1) <= slow_ma.shift(1))
        exits = (fast_ma < slow_ma) & (fast_ma.shift(1) >= slow_ma.shift(1))

        return entries.fillna(False), exits.fillna(False)

    return signal_fn
