"""
multi_ema_cci_trend_20260910.py - the six-EMA ribbon with a CCI zero trigger.

Location:  ~/src/trading/strategies/experimental/multi_ema_cci_trend_20260910.py

A ribbon of six exponential means says whether there is a trend and which way
it points; CCI crossing its zero line says the pullback inside that trend has
ended. The ribbon is the CONDITION and the CCI cross is the EVENT, and neither
trades alone: a ribbon test on its own is a trend-following entry at whatever
bar it happened to be read on, and a zero-line cross on its own fires in every
range in the sample.

================================================================================
STRATEGY SPECIFICATION & BACKTEST REQUEST  (filled from the 2026-09-10 request)
================================================================================
1. STRATEGY METADATA
   Strategy Name:       multi_ema_cci_trend
   Strategy Archetype:  Trend pullback / continuation
   Primary Timeframe:   15m  (TIMEFRAME; the ladder is TIMEFRAMES)
   Target Assets:       the 19-contract matrix (SYMBOLS)

2. CORE CONCEPT & HYPOTHESIS
   A trend is not one moving average, it is a set of them in agreement. When
   six means over {ribbon_count} horizons stack in order, every participant
   measuring the market on any of those horizons sees the same direction, and
   a pullback into the ribbon is where the ones who missed the move get their
   entry. The inefficiency harvested is that re-entry flow. It persists
   because the horizons are structural - different mandates measure trend over
   different windows - rather than a view. CCI crossing zero times the
   re-entry: it is the bar the pullback stops being a pullback.

3. INDICATORS & PARAMETER GRID
   EMA ribbon - {ribbon_count} means at {ribbon_step}, 2x{ribbon_step}, ...
       Default 4/8/12/16/20/24. Stacked in order is the strict condition; the
       relaxed one is Close above the slowest with a positive ribbon spread.
   CCI({cci_period}) - the trigger at {cci_trigger}, and the extreme at
       +/-{cci_extreme} for Version B's target.
   ATR(14), Wilder - the protective stop only, never a signal level.

4. ENTRY & EXIT EXECUTION RULES
   Long:   CCI({cci_period}) crosses ABOVE {cci_trigger} while the ribbon is
           aligned bullish.
   Short:  CCI crosses BELOW {cci_trigger} while the ribbon is aligned
           bearish.
   Exit:   ribbon breakdown - Close closing back through the slowest EMA -
           and the opposite CCI cross. Optionally the CCI extreme
           (use_cci_extreme_exit). A protective stop at {sl_atr_mult} x
           ATR(14) sits underneath all of them.
   Session Rules:   none modelled - NOT SPECIFIED in the request.
   Execution Fill:  next-bar open, engine-applied slippage and commission.

5. BACKTEST EXECUTION CONTROLS
   Repository defaults: in-sample 2013-01-01..2022-12-31, holdout 2023-01-01
   onward and untouched during optimisation, Version B evaluated against A.

THREE PLACES THE REQUEST LEFT A DECISION, MADE HERE AND FLAGGED
---------------------------------------------------------------
**"Version A / Version B" IN THE REQUEST IS NOT THIS REPOSITORY'S A/B.** The
Dual-Version Mandate is fixed: Version A is the rule-based baseline and
Version B is *the same signals* with an ML filter over them, generated by
`backtest/promote.py`'s wrapper and adopted only if it beats A out of sample.
The request's "Version A: EMA-anchored stop / Version B: trailing ATR with a
CCI target" describes two RISK CONFIGURATIONS of one rule set. Written as
versions they would collide with the mandate and Stage 3 would certify two
things that are not the pair it compares. They are therefore PARAMETERS and
the two configurations are named in `RISK_VARIANTS` below. DEFAULT_PARAMS is
the request's Version A, because that is the baseline this package is.

**"Stop loss anchored just below EMA_24 (or 2.0x ATR floor)" IS TWO DIFFERENT
MECHANISMS AND THE ENGINE ONLY HAS ONE OF THEM.** There are no stop ORDERS
here: `from_signals` is driven by boolean masks and the walk carries ONE stop
distance per position, frozen at the signal bar as `mult x ATR`. A stop
anchored to a moving average is a LEVEL that moves every bar, which that walk
cannot express and which no amount of multiplying an ATR reproduces.

So the two halves are implemented as the two things they actually are, and
the request's own exit list already names both: the EMA-24 anchor is the
RIBBON BREAKDOWN exit, a signal fired when Close closes back through the
slowest EMA (`use_ribbon_exit`), and the 2.0x ATR floor is the protective
bracket underneath it (`sl_atr_mult`). Naming them the same thing is exactly
how a stop distance ends up meaning two things, so both are spelled out.
`sl_atr_mult` is the ATR bracket and nothing else, and it is what
`promote.py` writes into the risk block.

**"Opposite CCI extreme profit target" is a SIGNAL exit, not a bracket.** A
target expressed as "CCI reaches +100" can only be an exit mask, detected on
the bar that reaches it and filled one bar later. `tp_atr_mult` stays None in
both variants rather than being fitted to approximate it, and
`use_cci_extreme_exit` carries the rule where it belongs.

WHAT THE ENGINE CANNOT DO, STATED SO NO DRAWDOWN IS MISREAD
------------------------------------------------------------
A stop is detected on the bar that breaches it and filled at the NEXT bar's
open, not at the stop price. Every drawdown figure this module produces is a
next-bar-open drawdown and is worse than a resting-order backtest would show.
The trailing stop in `RISK_VARIANTS["B_trailing"]` is a state machine inside
`_walk_loop`, and its high-water mark starts at the FILL bar, not the signal
bar.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from numpy.lib.stride_tricks import sliding_window_view


# ---------------------------------------------------------------------------
# The contract
# ---------------------------------------------------------------------------

#: The bar the DEFAULTS are set for, and the one the engine actually uses.
#: SINGULAR AND DECLARED: `agents.tier3_workers` reads
#: `getattr(module, "TIMEFRAME", None)` and its caller resolves
#: `explicit or info["timeframe"] or DEFAULT_TIMEFRAME`, where
#: DEFAULT_TIMEFRAME is "1d". Dropping this in favour of the plural below
#: would not raise - it would silently run an intraday ribbon on DAILY bars.
#: Nothing in this repository reads a `TIMEFRAMES`.
TIMEFRAME = "15m"

#: The ladder Stage 1 is meant to screen across. DESCRIPTIVE ONLY - no loader
#: or pipeline stage reads this name; a timeframe is selected per run with
#: `--timeframe`. Written down so the intended ladder is recoverable from the
#: module rather than from whoever typed the last command.
#:
#: 1m and 2m are absent deliberately: `intraday_start_year` exists because
#: pre-2013 1-minute data is sparse for ten symbols, and a 24-bar mean on
#: those bars describes the gaps as much as the tape.
TIMEFRAMES = ["5m", "15m", "30m", "1h"]

#: The 19-contract matrix. `python -m backtest.specs` reports UNVERIFIED for
#: M2K and MYM alone, and neither is here.
#:
#: A DECLARATION OF WHERE THE PREMISE MIGHT HOLD, NOT A CLAIM THAT IT DOES.
#: Cross-sectional by default: each contract is its own simulation on its own
#: multiplier, tick size and commission, and symbols are never blended into
#: one equity curve. Two carried caveats from CLAUDE.md, neither caught by the
#: spec reconciler because it checks the CONTRACT rather than the bars: SI
#: definitions stop at 2016 and CL at 2025-12.
SYMBOLS = ["ES", "NQ", "YM", "RTY", "CL", "NG", "RB", "HO", "GC", "SI", "PL",
           "6E", "6B", "6J", "6S", "ZB", "ZN", "BTC", "ETH"]

STRATEGY_NAME = "MULTI_EMA_CCI_TREND"
STRATEGY_MODULE = "multi_ema_cci_trend_20260910"

PORTFOLIO_GROUP = "Trend_Pullback"
CORRELATION_PROFILE = (
    "Spans every group in the matrix, so a basket drawn from it is only as "
    "diversified as the contracts chosen. The index names are one factor at "
    "four capitalisations and the energy names are another; routing sizes "
    "against that, not against the symbol count.")

#: The regime the premise NOMINATES. Stage 1 designates the real one by
#: measuring all four quadrants, and nothing here reads these. Quadrant ids
#: are `mdlib/regimes.py`'s: Q1 High-Vol/Trending, Q2 High-Vol/Ranging,
#: Q3 Low-Vol/Trending, Q4 Low-Vol/Ranging, 0 UNDEFINED (warm-up, not a
#: quadrant). A ribbon-alignment premise nominates the TRENDING pair - in a
#: ranging regime the ribbon spends its time tangled and the alignment test
#: is measuring noise, which is what Gate R settles rather than this
#: declaration.
TARGET_REGIMES = ("High Volatility / Trending", "Low Volatility / Trending")
TARGET_QUADRANTS = ("Q1", "Q3")

#: Wilder's ATR period, for the protective stop only. Fixed at 14 rather than
#: exposed: it never enters a signal level, so sweeping it would move only the
#: stop and confound the ribbon study it sits under.
ATR_PERIOD = 14

#: A stop nearer than this to the fill sits inside the bar's own noise and the
#: run measures the cost model rather than the strategy.
MIN_STOP_ATR_MULT = 0.25

#: Lambert's constant. CCI is defined as
#: `(TP - SMA(TP)) / (0.015 * mean absolute deviation)`, and the 0.015 is what
#: puts roughly 70-80% of readings inside +/-100 - which is the entire meaning
#: of the +/-{cci_extreme} levels the request uses as a target. Named rather
#: than inlined so a reader can check it against the definition instead of
#: finding a bare 0.015 in a division.
CCI_CONSTANT = 0.015


DEFAULT_PARAMS = {
    "ribbon_step": 4,
    "ribbon_count": 6,
    "cci_period": 14,
    "cci_trigger": 0.0,
    "cci_extreme": 100.0,
    "require_strict_stack": False,
    "use_ribbon_exit": True,
    "use_cci_extreme_exit": False,
    "sl_atr_mult": 2.0,
    "tp_atr_mult": None,
    "trailing": False,
}

#: THE TWO CONFIGURATIONS THE REQUEST CALLED "Version A" AND "Version B".
#:
#: They are risk configurations of one rule set, NOT this repository's A/B -
#: see the module docstring. Named here so the request is recoverable from the
#: module and so a run can bind either without the numbers being retyped, and
#: kept out of PARAM_GRID because sweeping a bundle would confound which of
#: its changes moved the result.
#:
#: `A_ribbon` is DEFAULT_PARAMS and is what this package is certified as. Its
#: "stop anchored below EMA_24" is `use_ribbon_exit`, a SIGNAL, with the 2.0x
#: ATR bracket underneath - see the module docstring for why those are two
#: mechanisms and not one.
RISK_VARIANTS = {
    "A_ribbon": {
        "sl_atr_mult": 2.0,
        "tp_atr_mult": None,
        "trailing": False,
        "use_ribbon_exit": True,
        "use_cci_extreme_exit": False,
    },
    "B_trailing": {
        "sl_atr_mult": 2.5,
        "tp_atr_mult": None,
        "trailing": True,
        "use_ribbon_exit": False,
        "use_cci_extreme_exit": True,
    },
}

#: The search space `backtest/run.py --scan` sweeps.
#:
#:     3 x 3 x 2 x 2 = 36 combinations
#:
#: Coarse on purpose. `variants_tested` travels with every result precisely so
#: a reader can see how large the search was that produced a Sharpe; a 400-cell
#: grid over the same bars is a machine for manufacturing an in-sample Sharpe.
#:
#: `ribbon_step` sweeps the ribbon's SPACING while keeping its shape - six
#: means evenly spaced is the premise, and 4 is the request's default sitting
#: inside the range rather than at its edge. `require_strict_stack` is swept
#: because the request declared the strict and relaxed alignments with an
#: "or" and did not say which binds; the sweep answers it instead of whoever
#: wrote the module.
#:
#: `cci_trigger` is pinned at the request's 0.0 and NOT swept. It is the
#: definition of the event - the bar the pullback ends - and a swept trigger
#: level is a different strategy at every value rather than the same one
#: measured more carefully.
PARAM_GRID = {
    "ribbon_step": [3, 4, 6],
    "cci_period": [10, 14, 20],
    "sl_atr_mult": [1.5, 2.0],
    "require_strict_stack": [True, False],
}

LOGIC = {
    "concept": (
        "A trend is not one moving average but {ribbon_count} of them in "
        "agreement. Six EMAs spaced {ribbon_step} bars apart stack in order "
        "when every horizon sees the same direction, and a pullback into that "
        "ribbon is where the flow that missed the move re-enters. "
        "CCI({cci_period}) crossing {cci_trigger} times it: that is the bar "
        "the pullback stops being a pullback. The ribbon is the CONDITION and "
        "the cross is the EVENT - neither trades alone. Trades are attributed "
        "by their ENTRY bar, never the exit, so a move opened in one quadrant "
        "that runs into another still scores where it opened."),
    "entry": (
        "LONG when CCI({cci_period}) crosses ABOVE {cci_trigger} while the "
        "ribbon is aligned bullish; SHORT when it crosses BELOW while the "
        "ribbon is aligned bearish. Alignment is the EMAs stacked in order, "
        "or - with require_strict_stack={require_strict_stack} - the relaxed "
        "form: Close beyond the slowest EMA with the ribbon spread on the "
        "same side of zero."),
    "exit": (
        "The opposite CCI cross always closes the position. With "
        "use_ribbon_exit={use_ribbon_exit} a Close back through the SLOWEST "
        "EMA closes it too - that is the request's stop 'anchored just below "
        "EMA_24', and it is a SIGNAL because the engine has no stop orders. "
        "With use_cci_extreme_exit={use_cci_extreme_exit} the opposite CCI "
        "extreme (+/-{cci_extreme}) closes it as well. A protective bracket "
        "at {sl_atr_mult} x ATR(14) sits underneath all of them, "
        "trailing={trailing}; no ATR take-profit is modelled "
        "(tp_atr_mult={tp_atr_mult})."),
}


# ---------------------------------------------------------------------------
# Indicator kernels
#
# `_ema`, `_wilder`, `_true_range`, `_atr`, `_as_series`, `_cross_above`,
# `_cross_below` and `_walk_loop` below are DUPLICATED VERBATIM from
# `semafor_ha_momentum_20260910.py`, which shares them with the rest of this
# directory. Strategy modules are loaded from a FILE PATH by
# `agents.tier3_workers.load_strategy` and promoted as a self-contained copy,
# so a shared import would resolve against whatever happens to sit beside the
# module at load time - and a promoted package must reproduce the file that
# was certified, byte for byte. Do not "improve" one alone.
# ---------------------------------------------------------------------------
def _ema(series: pd.Series, period: int) -> pd.Series:
    """
    A span-`period` exponential mean, NaN until `period` bars exist.

    `min_periods=period` rather than pandas' default of 1: without it the
    first bar's EMA is that bar's own close, which is not an average of
    anything, and a ribbon built from it is stacked in whatever order the
    first bar happened to imply.
    """
    return series.ewm(span=period, adjust=False, min_periods=period).mean()


def _wilder(series: pd.Series, period: int) -> pd.Series:
    """
    Wilder's smoothing - the average the ATR is actually defined on.

    `alpha = 1/period` with `adjust=False` is Wilder's recursion exactly. A
    span-`period` EMA (`_ema` above) is a different, roughly twice as fast,
    average, and using it here would produce an "ATR(14)" that no other tool
    agrees with - so a reader checking a stop distance against their own chart
    would see it somewhere else.
    """
    return series.ewm(alpha=1.0 / period, adjust=False,
                      min_periods=period).mean()


def _true_range(bars: pd.DataFrame) -> pd.Series:
    """
    True range per bar.

    `.shift(1)` looks one bar BACKWARD, which is the correct direction: the
    true range at bar i uses bar i-1's close and nothing later.
    """
    high, low, close = bars["high"], bars["low"], bars["close"]
    prev = close.shift(1)
    return pd.concat([(high - low).abs(),
                      (high - prev).abs(),
                      (low - prev).abs()], axis=1).max(axis=1)


def _atr(bars: pd.DataFrame, period: int = ATR_PERIOD) -> pd.Series:
    """
    True range, Wilder-smoothed. NaN until `period` bars exist.

    A ZERO ATR IS A MEASUREMENT, NOT A GAP, and it is left as the 0.0 it is.
    A window in which nothing moved - a halted contract, a dead overnight
    hour - has a true ATR of zero. `signal_fn` refuses to enter on such a bar
    rather than placing a bracket of zero width around the fill.
    """
    return _wilder(_true_range(bars), period)


def _as_series(value, index) -> pd.Series:
    """A scalar level as a Series on `index`; a Series is returned as-is."""
    if isinstance(value, pd.Series):
        return value
    return pd.Series(float(value), index=index)


def _cross_above(fast: pd.Series, level) -> pd.Series:
    """
    True on the bar `fast` crosses UP through `level` - a series or a scalar.

        fast[i] > level[i]  AND  fast[i-1] <= level[i-1]

    A STATE (`fast > level`) would be true for every bar of a run; this is the
    EVENT, true once. `<=` on the previous bar rather than `<` so a pair that
    was exactly equal and then separated counts as a cross - with two
    oscillators quantised by the same price series, exact equality is not the
    measure-zero event it is for two continuous curves.

    NaN-SAFE BY CONSTRUCTION: every comparison against NaN is False, so a
    warm-up bar is never a cross. `.shift(1)` looks one bar BACKWARD.
    """
    other = _as_series(level, fast.index)
    return (fast > other) & (fast.shift(1) <= other.shift(1))


def _cross_below(fast: pd.Series, level) -> pd.Series:
    """
    True on the bar `fast` crosses DOWN through `level`. The exact mirror of
    `_cross_above`, written out rather than expressed as its negation:
    `~_cross_above` is true on every bar that merely fails to be a cross up,
    which is almost all of them.
    """
    other = _as_series(level, fast.index)
    return (fast < other) & (fast.shift(1) >= other.shift(1))


def _mean_abs_dev(values: pd.Series, period: int) -> pd.Series:
    """
    Rolling mean absolute deviation about the rolling mean - CCI's denominator.

    MAD HAS NO CLOSED FORM the way a variance does: `E|x - mean|` cannot be
    accumulated from running sums, so it is computed over an explicit window.
    `sliding_window_view` is a VIEW rather than a copy, and only the
    subtraction materialises - one `(n_bars, period)` float array, about 50 MB
    at 5m over sixteen years and 16 MB at 15m. That is the cost of the exact
    definition, and it is paid here rather than approximated with a standard
    deviation, which is a DIFFERENT denominator: CCI computed against SD reads
    roughly 20% smaller and its +/-100 levels then mean something no chart
    agrees with.

    `rolling.apply` would avoid the array and call back into Python once per
    window - hundreds of thousands of times per symbol - so it is slower by
    orders of magnitude for an identical answer.

    Strictly causal: window `i` spans bars `i - period + 1 .. i`.
    """
    n = int(period)
    arr = values.to_numpy(dtype="float64")
    out = np.full(arr.shape[0], np.nan)
    if arr.shape[0] >= n:
        win = sliding_window_view(arr, n)
        out[n - 1:] = np.abs(win - win.mean(axis=1, keepdims=True)).mean(axis=1)
    return pd.Series(out, index=values.index)


def _cci(bars: pd.DataFrame, period: int) -> pd.Series:
    """
    Commodity Channel Index on the typical price. NaN until `period` bars.

        TP  = (high + low + close) / 3
        CCI = (TP - SMA(TP, n)) / (CCI_CONSTANT * MAD(TP, n))

    A zero MAD - a window in which the typical price never moved - would
    divide by zero. It is mapped to NaN rather than to 0 or to a large number,
    because every comparison against NaN is False, so a dead window is never a
    cross in either direction.
    """
    tp = (bars["high"].astype("float64")
          + bars["low"].astype("float64")
          + bars["close"].astype("float64")) / 3.0
    sma = tp.rolling(int(period), min_periods=int(period)).mean()
    mad = _mean_abs_dev(tp, int(period)).replace(0.0, np.nan)
    return (tp - sma) / (CCI_CONSTANT * mad)


def _ribbon_periods(step: int, count: int) -> list[int]:
    """
    The ribbon's periods: `step, 2*step, ... count*step`.

    Derived rather than listed so the spacing is one sweepable number. The
    request's 4/8/12/16/20/24 is `step=4, count=6`, which is DEFAULT_PARAMS.
    """
    return [int(step) * (i + 1) for i in range(int(count))]


def _walk_loop(long_entry_ok: np.ndarray,
               short_entry_ok: np.ndarray,
               long_sig_exit: np.ndarray,
               short_sig_exit: np.ndarray,
               open_: np.ndarray,
               high: np.ndarray,
               low: np.ndarray,
               atr: np.ndarray,
               flat_bar: np.ndarray,
               sl_mult: float,
               tp_mult: float,
               trailing: bool) -> tuple[np.ndarray, np.ndarray,
                                        np.ndarray, np.ndarray,
                                        np.ndarray, np.ndarray]:
    """
    THREE-state machine over the bars: flat, long, or short - each side under
    its own stop, target and signal exit.

    DUPLICATED VERBATIM from `semafor_ha_momentum_20260910.py`, which shares
    it with `dbb_momentum_breakout_20260909.py`,
    `keltner_trend_drift_20260901.py`, `sma_momentum_crossover_20260818.py`,
    `t3_braid_scalp_20260823.py` and `ema_crossover_20260821.py`, by the same
    convention that duplicates `_wilder` and `_atr` across this directory. Do
    not "improve" one alone.

    The timeline matches the engine's. An entry signal on bar i is filled at
    bar i+1's open, so the position is live from bar i+1, the fill price is
    `open_[i + 1]`, and the extreme-price mark starts there - NOT on the
    signal bar. Both distances are frozen at `mult * ATR` as measured on the
    SIGNAL bar and never re-measured as volatility changes.

    The two sides, written out rather than folded into a sign flip, because a
    reader has to be able to check them against the specification by eye:

        LONG    stop     fill - dist    trailing: (highest high since fill) - dist
                target   fill + dist
                exits    low  <= stop   or  high >= target
        SHORT   stop     fill + dist    trailing: (lowest low   since fill) + dist
                target   fill - dist
                exits    high >= stop   or  low  <= target

    A short stop placed BELOW the fill would be breached by the fill bar
    itself; this is the reason the sides are not a sign flip.

    `tp_mult` is NaN when no take-profit is modelled, rather than a sentinel
    like 0 or a huge number. NaN propagates into `target` and every comparison
    against it is False, so the target simply never fires on either side.

    A bar carrying BOTH a long and a short entry signal while flat takes
    NEITHER, matching `backtest.engine._clean_signals_ls_loop`. A well-formed
    strategy cannot produce it - CCI cannot cross above and below zero on one
    bar - so the branch exists to make a malformed one visible as a missing
    trade rather than a plausible one-sided curve.

    A position is never reversed directly. The walk enters only from flat, so
    a short signal arriving while long is ignored; the long must exit first.

    Exits are checked from the fill bar onward, never on the signal bar.
    """
    n = long_entry_ok.shape[0]
    long_entries = np.zeros(n, dtype=np.bool_)
    long_exits = np.zeros(n, dtype=np.bool_)
    short_entries = np.zeros(n, dtype=np.bool_)
    short_exits = np.zeros(n, dtype=np.bool_)
    stop_level = np.full(n, np.nan)
    tp_level = np.full(n, np.nan)

    state = 0                            # 0 flat, 1 long, -1 short
    fill_i = 0
    stop_dist = 0.0
    tp_dist = np.nan
    entry_px = np.nan
    hw = 0.0                             # highest high since the fill (long)
    lw = 0.0                             # lowest low since the fill (short)

    for i in range(n):
        if state == 0:
            go_long = long_entry_ok[i]
            go_short = short_entry_ok[i]
            if go_long and go_short:
                continue                 # ambiguous bar: take neither side
            if go_long or go_short:
                fill_i = i + 1
                stop_dist = sl_mult * atr[i]
                # NaN in, NaN out: no take-profit stays no take-profit.
                tp_dist = tp_mult * atr[i]
                entry_px = np.nan
                hw = -np.inf
                lw = np.inf
                if go_long:
                    long_entries[i] = True
                    state = 1
                else:
                    short_entries[i] = True
                    state = -1
            continue

        if i < fill_i:
            continue

        if i == fill_i:
            # The engine's own fill: the open of the bar AFTER the signal. Not
            # the signal bar's close, which the position never traded at.
            entry_px = open_[i]

        if state == 1:
            if trailing:
                if high[i] > hw:
                    hw = high[i]
                level = hw - stop_dist
            else:
                level = entry_px - stop_dist

            target = entry_px + tp_dist   # NaN when no target is modelled
            stop_level[i] = level
            tp_level[i] = target

            hit_stop = low[i] <= level
            # False whenever `target` is NaN, which is how "no take-profit" is
            # expressed. Every comparison against NaN is False in both numba
            # and numpy, so the interpreted fallback cannot disagree with the
            # compiled loop about it.
            hit_tp = high[i] >= target

            # A bar that breaches both produces one exit on this bar either
            # way, and the engine fills it at the next bar's open regardless -
            # so the intrabar race between the stop and the target is not
            # resolved here because it cannot change the result.
            if hit_stop or hit_tp or long_sig_exit[i] or flat_bar[i]:
                long_exits[i] = True
                state = 0
        else:
            if trailing:
                if low[i] < lw:
                    lw = low[i]
                level = lw + stop_dist
            else:
                level = entry_px + stop_dist

            target = entry_px - tp_dist   # NaN when no target is modelled
            stop_level[i] = level
            tp_level[i] = target

            hit_stop = high[i] >= level
            hit_tp = low[i] <= target     # False when target is NaN

            if hit_stop or hit_tp or short_sig_exit[i] or flat_bar[i]:
                short_exits[i] = True
                state = 0

    return (long_entries, long_exits, short_entries, short_exits,
            stop_level, tp_level)


try:                                    # pragma: no cover - env dependent
    from numba import njit

    # No `cache=True`. `load_strategy` imports this module from a file path,
    # so it is not importable by name. Compiling still works and numba writes
    # the cache; it is the LOAD in a later process that fails, with
    # `ModuleNotFoundError: No module named '<dynamic>'`, which is why the
    # first run after a cache wipe looks clean and the second one dies.
    _walk = njit(nogil=True)(_walk_loop)
except ImportError:                     # pragma: no cover - env dependent
    # Same function, interpreted. `backtest.engine.clean_signals` degrades the
    # same way, and the fallback has to exist because a missing compiler must
    # not change which trades a strategy takes.
    _walk = _walk_loop


# --------------------------------------------------------------------------
# Validation
# --------------------------------------------------------------------------
def _validate(ribbon_step: int, ribbon_count: int, cci_period: int,
              cci_trigger: float, cci_extreme: float, sl_atr_mult: float,
              tp_atr_mult: float | None, trailing: bool) -> None:
    """
    Refuse a parameter set that cannot mean what it says, where it is passed
    rather than as a strange equity curve. Each has a specific failure behind
    it:

    * `ribbon_step < 1` gives two EMAs the same period, so the ribbon is
      "stacked" on every bar by definition and the alignment test admits
      everything.
    * `ribbon_count < 2` is not a ribbon: with one mean there is no ordering
      to check and no spread to sign.
    * `cci_period < 2` makes the mean absolute deviation zero on every window,
      so CCI is NaN throughout and nothing ever crosses.
    * `cci_extreme <= |cci_trigger|` puts the target at or inside the trigger,
      so `use_cci_extreme_exit` closes a position on the bar that opened it.
    * A stop inside MIN_STOP_ATR_MULT sits inside the bar's own noise.
    * `tp_atr_mult` may be None - that IS a setting, meaning "no target" - but
      a non-positive number would put the target at or behind the fill and
      close every trade on its first bar.
    """
    if int(ribbon_step) < 1:
        raise ValueError(
            f"ribbon_step must be >= 1; got {ribbon_step!r}. Below that two "
            f"EMAs share a period and the ribbon is 'stacked' on every bar.")
    if int(ribbon_count) < 2:
        raise ValueError(
            f"ribbon_count must be >= 2; got {ribbon_count!r}. One mean has "
            f"no ordering to check and no spread to sign.")
    if int(cci_period) < 2:
        raise ValueError(
            f"cci_period must be >= 2; got {cci_period!r}. Below that the "
            f"mean absolute deviation is zero on every window and CCI is NaN "
            f"throughout, so nothing ever crosses.")
    if float(cci_extreme) <= abs(float(cci_trigger)):
        raise ValueError(
            f"cci_extreme must be > |cci_trigger|; got "
            f"extreme={cci_extreme!r} and trigger={cci_trigger!r}. At or "
            f"inside the trigger, use_cci_extreme_exit closes a position on "
            f"the bar that opened it.")
    if float(sl_atr_mult) < MIN_STOP_ATR_MULT:
        raise ValueError(
            f"sl_atr_mult must be >= {MIN_STOP_ATR_MULT}; got "
            f"{sl_atr_mult!r}. A tighter stop sits inside the bar's own noise "
            f"and the run measures the cost model.")
    if tp_atr_mult is not None and float(tp_atr_mult) <= 0.0:
        raise ValueError(
            f"tp_atr_mult must be > 0 or None (no target); got "
            f"{tp_atr_mult!r}. At or below zero the target sits at or behind "
            f"the fill and every trade closes on its first bar.")
    if not isinstance(trailing, (bool, np.bool_)):
        raise ValueError(f"trailing must be a bool; got {trailing!r}")


def _tp_distance(tp_atr_mult: float | None) -> float:
    """
    The take-profit multiple as the walk wants it: NaN for "no target".

    NaN rather than 0 or a large sentinel, because every comparison against
    NaN is False in both the compiled and the interpreted loop - so the target
    never fires and the drawn line is a visible gap.
    """
    if tp_atr_mult is None:
        return float("nan")
    return float(tp_atr_mult)


# --------------------------------------------------------------------------
# Layers
# --------------------------------------------------------------------------
def _layers(bars: pd.DataFrame, ribbon_step: int, ribbon_count: int,
            cci_period: int, cci_trigger: float, cci_extreme: float,
            require_strict_stack: bool, use_ribbon_exit: bool,
            use_cci_extreme_exit: bool) -> dict[str, pd.Series]:
    """
    Every series both `signal_fn` and `indicators` read, computed ONCE.

    One call site for the maths is the point: a second implementation in the
    report would be free to disagree with this one and draw a cross a bar from
    where the trade fired, with nothing raising.

    The toggles live here rather than in `signal_fn` so a disabled filter is a
    Series of True with the underlying series still computed and still drawn -
    a reader can see what the filter WOULD have said on a run where it was off.
    """
    close = bars["close"].astype("float64")
    periods = _ribbon_periods(ribbon_step, ribbon_count)
    ribbon = {p: _ema(close, p) for p in periods}
    fastest, slowest = ribbon[periods[0]], ribbon[periods[-1]]
    cci = _cci(bars, int(cci_period))
    atr = _atr(bars, ATR_PERIOD)

    # THE STRICT STACK. Written as the pairwise chain the specification names
    # - EMA_4 > EMA_8 > ... > EMA_24 - rather than as a sort or a rank, so a
    # reader can check it against the request by eye and so the SHORT side is
    # a separate chain rather than a negation. `~(a > b)` is true when they
    # are equal, which on a tangled ribbon is most of the time.
    stack_long = pd.Series(True, index=bars.index)
    stack_short = pd.Series(True, index=bars.index)
    for fast_p, slow_p in zip(periods, periods[1:]):
        stack_long = stack_long & (ribbon[fast_p] > ribbon[slow_p])
        stack_short = stack_short & (ribbon[fast_p] < ribbon[slow_p])

    # THE RELAXED ALIGNMENT the request offers as the alternative: price
    # beyond the slowest mean with the ribbon spread on the same side of zero.
    # The spread is fastest minus slowest, which is the ribbon's own width AND
    # its direction in one number.
    spread = fastest - slowest
    relaxed_long = (close > slowest) & (spread > 0.0)
    relaxed_short = (close < slowest) & (spread < 0.0)

    if require_strict_stack:
        align_long, align_short = stack_long, stack_short
    else:
        align_long = stack_long | relaxed_long
        align_short = stack_short | relaxed_short

    # A NaN anywhere in the ribbon is warm-up, and `True & NaN-comparison` is
    # False already - but the slowest EMA warms up last and is what both
    # alignments rest on, so it is the one masked explicitly.
    warm = slowest.isna() | cci.isna()
    align_long = align_long & ~warm
    align_short = align_short & ~warm

    # THE TRIGGER IS A CROSS, NOT A STATE. CCI above zero is true for every
    # bar of a leg; the event is the bar it got there.
    cci_up = _cross_above(cci, float(cci_trigger))
    cci_down = _cross_below(cci, float(cci_trigger))

    trigger_long = cci_up & align_long
    trigger_short = cci_down & align_short

    # THE EXITS. The opposite CCI cross is unconditional: the pullback the
    # entry was timed on has reversed. The other two are the request's two
    # risk configurations and are toggles.
    exit_long = cci_down.copy()
    exit_short = cci_up.copy()
    if use_ribbon_exit:
        # The request's stop "anchored just below EMA_24". A SIGNAL, not a
        # bracket - see the module docstring - so it is a close back through
        # the slowest EMA rather than a level the walk could carry.
        exit_long = exit_long | _cross_below(close, slowest)
        exit_short = exit_short | _cross_above(close, slowest)
    if use_cci_extreme_exit:
        exit_long = exit_long | _cross_above(cci, float(cci_extreme))
        exit_short = exit_short | _cross_below(cci, -float(cci_extreme))

    out = {
        "close": close, "cci": cci, "atr": atr,
        "fastest": fastest, "slowest": slowest, "spread": spread,
        "stack_long": stack_long, "stack_short": stack_short,
        "relaxed_long": relaxed_long, "relaxed_short": relaxed_short,
        "align_long": align_long, "align_short": align_short,
        "cci_up": cci_up, "cci_down": cci_down,
        "trigger_long": trigger_long, "trigger_short": trigger_short,
        "exit_long": exit_long, "exit_short": exit_short,
        "spread_norm": spread / atr.replace(0.0, np.nan),
        "dist_slowest_atr": (close - slowest) / atr.replace(0.0, np.nan),
    }
    for p in periods:
        out[f"ema_{p}"] = ribbon[p]
    out["ribbon_periods"] = periods
    return out


# --------------------------------------------------------------------------
# The contract functions
# --------------------------------------------------------------------------
def signal_fn(bars: pd.DataFrame,
              ribbon_step: int = 4,
              ribbon_count: int = 6,
              cci_period: int = 14,
              cci_trigger: float = 0.0,
              cci_extreme: float = 100.0,
              require_strict_stack: bool = False,
              use_ribbon_exit: bool = True,
              use_cci_extreme_exit: bool = False,
              sl_atr_mult: float = 2.0,
              tp_atr_mult: float | None = None,
              trailing: bool = False) -> tuple[pd.Series, pd.Series,
                                               pd.Series, pd.Series]:
    """
    Returns the FOUR-MASK form: (long_entries, long_exits, short_entries,
    short_exits), all boolean Series on `bars.index`.

    A three-tuple or a bare Series RAISES in `engine.unpack_signals` rather
    than silently losing the short side into a plausible long-only curve.

    THE SHORT SIDE IS NOT THE LONG SIDE WITH A SIGN FLIP. Inside `_walk_loop`
    the short stop sits ABOVE the fill; placed below it, the fill bar itself
    would breach it. The masks are written out per side for the same reason.

    NOTHING HERE READS A BAR LATER THAN i: no negative shift appears anywhere
    in this module, and every rolling window ends at the bar it describes.
    """
    _validate(ribbon_step, ribbon_count, cci_period, cci_trigger, cci_extreme,
              sl_atr_mult, tp_atr_mult, trailing)

    L = _layers(bars, int(ribbon_step), int(ribbon_count), int(cci_period),
                float(cci_trigger), float(cci_extreme),
                bool(require_strict_stack), bool(use_ribbon_exit),
                bool(use_cci_extreme_exit))

    long_ok = L["trigger_long"].fillna(False).to_numpy()
    short_ok = L["trigger_short"].fillna(False).to_numpy()
    long_sig_exit = L["exit_long"].fillna(False).to_numpy()
    short_sig_exit = L["exit_short"].fillna(False).to_numpy()

    atr = L["atr"].to_numpy(dtype="float64")
    # A bar with no ATR yet is not tradable: the protective bracket has no
    # width, and admitting it would place a stop at the fill price.
    warm = ~np.isfinite(atr) | (atr <= 0.0)
    # The ribbon warms up on a longer window than the ATR whenever
    # ribbon_step * ribbon_count exceeds it, and the alignment test rests on
    # the slowest mean. A NaN there already makes both alignments False;
    # masking it explicitly keeps that true however the periods are swept.
    warm = warm | ~np.isfinite(L["slowest"].to_numpy(dtype="float64"))
    warm = warm | ~np.isfinite(L["cci"].to_numpy(dtype="float64"))
    long_ok = long_ok & ~warm
    short_ok = short_ok & ~warm

    flat_bar = np.zeros(len(bars), dtype=bool)

    le, lx, se, sx, _, _ = _walk(
        long_ok, short_ok, long_sig_exit, short_sig_exit,
        bars["open"].to_numpy(dtype="float64"),
        bars["high"].to_numpy(dtype="float64"),
        bars["low"].to_numpy(dtype="float64"),
        np.nan_to_num(atr, nan=0.0), flat_bar, float(sl_atr_mult),
        _tp_distance(tp_atr_mult), bool(trailing))

    idx = bars.index
    return (pd.Series(le, index=idx), pd.Series(lx, index=idx),
            pd.Series(se, index=idx), pd.Series(sx, index=idx))


def generate_signals(df: pd.DataFrame, params: dict | None = None
                     ) -> tuple[pd.Series, pd.Series, pd.Series, pd.Series]:
    """
    The `generate_signals(df, params)` calling convention, as a thin adapter.

    NOT THE ENGINE'S ENTRY POINT. `agents.tier3_workers.load_strategy` binds
    `make_signal_fn(**params)` or `signal_fn(bars, **params)` and knows
    nothing about this name. It delegates rather than reimplementing, so the
    two can never disagree about what a signal is.
    """
    bound = {**DEFAULT_PARAMS, **(params or {})}
    unknown = set(bound) - set(DEFAULT_PARAMS)
    if unknown:
        raise ValueError(f"unknown parameter(s): {sorted(unknown)}")
    return signal_fn(df, **bound)


def indicators(bars: pd.DataFrame, **params) -> dict[str, pd.Series]:
    """
    Full-length series drawn over the trade inspector's candles, from the same
    `_layers` call `signal_fn` uses - so the chart cannot draw a cross a bar
    from where the entry actually happened.

    Every ribbon member is drawn, not just the fastest and slowest: the
    ALIGNMENT is the signal, and a chart showing two of six means cannot show
    a reader why a bar was aligned or was not.
    """
    p = {**DEFAULT_PARAMS, **(params or {})}
    L = _layers(bars, int(p["ribbon_step"]), int(p["ribbon_count"]),
                int(p["cci_period"]), float(p["cci_trigger"]),
                float(p["cci_extreme"]), bool(p["require_strict_stack"]),
                bool(p["use_ribbon_exit"]), bool(p["use_cci_extreme_exit"]))
    drawn = {f"EMA({period})": L[f"ema_{period}"]
             for period in L["ribbon_periods"]}
    drawn[f"CCI({int(p['cci_period'])})"] = L["cci"]
    drawn[f"ATR({ATR_PERIOD})"] = L["atr"]
    return drawn


def ml_features(bars: pd.DataFrame, **params) -> pd.DataFrame:
    """
    The matrix Version B's classifier is fitted on: one row per bar, in order.

    CAUSALITY IS THIS MODULE'S RESPONSIBILITY. Every column is built from
    `_layers`, which reads only bars <= i, and nothing is scaled against the
    whole frame - a scaler fitted end to end leaks the test period's
    distribution into the training rows without tripping any shift-based
    audit.

    SHAPE IS CHECKED BY THE CALLER AND A FAILURE RAISES - unlike `indicators`,
    which is wrapped, because a broken chart annotation must not throw away a
    completed backtest but a silently swapped feature matrix must not survive
    one.

    The columns are the state the RULES read, as RATIOS rather than levels. A
    ribbon spread of 12.5 points means nothing across contracts, and a
    classifier fitted on levels learns the symbol rather than the setup. The
    per-member gaps are normalised the same way, so a ribbon that is merely
    wide is distinguishable from one that is evenly ordered.
    """
    p = {**DEFAULT_PARAMS, **(params or {})}
    L = _layers(bars, int(p["ribbon_step"]), int(p["ribbon_count"]),
                int(p["cci_period"]), float(p["cci_trigger"]),
                float(p["cci_extreme"]), bool(p["require_strict_stack"]),
                bool(p["use_ribbon_exit"]), bool(p["use_cci_extreme_exit"]))
    close = L["close"]
    atr = L["atr"].replace(0.0, np.nan)
    periods = L["ribbon_periods"]
    cols = {
        "cci": L["cci"],
        "spread_norm": L["spread_norm"],
        "dist_slowest_atr": L["dist_slowest_atr"],
        "dist_fastest_atr": (close - L["fastest"]) / atr,
        "stack_long": L["stack_long"].astype("float64"),
        "stack_short": L["stack_short"].astype("float64"),
        "norm_atr": atr / close,
        "roc_3": close.pct_change(3),
        "roc_10": close.pct_change(10),
        "range_atr": (bars["high"] - bars["low"]) / atr,
    }
    # The gaps BETWEEN consecutive means, normalised. A ribbon can be wide and
    # tangled or narrow and perfectly ordered, and the spread alone cannot
    # tell those apart - which is the distinction the alignment test makes.
    for fast_p, slow_p in zip(periods, periods[1:]):
        cols[f"gap_{fast_p}_{slow_p}_atr"] = (
            (L[f"ema_{fast_p}"] - L[f"ema_{slow_p}"]) / atr)
    volume = (bars["volume"].astype("float64") if "volume" in bars.columns
              else pd.Series(np.nan, index=bars.index))
    vol_sma = volume.rolling(20, min_periods=20).mean().shift(1)
    vol_std = volume.rolling(20, min_periods=20).std().shift(1)
    cols["volume_z"] = (volume - vol_sma) / vol_std.replace(0.0, np.nan)
    out = pd.DataFrame(cols, index=bars.index)
    return out.replace([np.inf, -np.inf], np.nan).fillna(0.0)


def make_signal_fn(**params):
    """The parameterised form `load_strategy` prefers. Binds `params` once and
    returns the one-argument callable the engine walks."""
    bound = {**DEFAULT_PARAMS, **(params or {})}
    unknown = set(bound) - set(DEFAULT_PARAMS)
    if unknown:
        # Raise rather than ignore. A stale grid key silently dropped would
        # sweep the DEFAULT and report it under the swept name.
        raise ValueError(f"unknown parameter(s): {sorted(unknown)}")

    def _fn(bars: pd.DataFrame):
        return signal_fn(bars, **bound)
    return _fn
